id: A6BBDCF75
title: Aspiration to Be Cared for in Every Lifetime
type: translation
pechas:
- I4FFD8AB1
- IB4199A99
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:22.462043
  last_modified_at: 2023-01-04 12:49:22.462060
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I4FFD8AB1/446E: D002
  IB4199A99/9F45: D002
